// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message.proto

package com.avast.cactus;

public final class TestMessage {
  private TestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string field = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    boolean hasField();
    /**
     * <code>optional string field = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    String getField();
    /**
     * <code>optional string field = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    com.google.protobuf.ByteString
        getFieldBytes();

    /**
     * <code>optional int32 field_int_name = 2;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    boolean hasFieldIntName();
    /**
     * <code>optional int32 field_int_name = 2;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    int getFieldIntName();

    /**
     * <code>optional int32 field_option = 3;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    boolean hasFieldOption();
    /**
     * <code>optional int32 field_option = 3;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    int getFieldOption();

    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getFieldStringsList();
    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    int getFieldStringsCount();
    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    String getFieldStrings(int index);
    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    com.google.protobuf.ByteString
        getFieldStringsBytes(int index);

    /**
     * <code>repeated int32 field_option_integers = 5;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    java.util.List<Integer> getFieldOptionIntegersList();
    /**
     * <code>repeated int32 field_option_integers = 5;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    int getFieldOptionIntegersCount();
    /**
     * <code>repeated int32 field_option_integers = 5;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    int getFieldOptionIntegers(int index);

    /**
     * <code>optional .Data2 field_gpb_option = 6;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    boolean hasFieldGpbOption();
    /**
     * <code>optional .Data2 field_gpb_option = 6;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    Data2 getFieldGpbOption();
    /**
     * <code>optional .Data2 field_gpb_option = 6;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    Data2OrBuilder getFieldGpbOptionOrBuilder();

    /**
     * <code>optional .Data2 field_gpb_option_empty = 7;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    boolean hasFieldGpbOptionEmpty();
    /**
     * <code>optional .Data2 field_gpb_option_empty = 7;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    Data2 getFieldGpbOptionEmpty();
    /**
     * <code>optional .Data2 field_gpb_option_empty = 7;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    Data2OrBuilder getFieldGpbOptionEmptyOrBuilder();

    /**
     * <code>optional .Data2 field_gpb = 8;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    boolean hasFieldGpb();
    /**
     * <code>optional .Data2 field_gpb = 8;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    Data2 getFieldGpb();
    /**
     * <code>optional .Data2 field_gpb = 8;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    Data2OrBuilder getFieldGpbOrBuilder();
  }
  /**
   * Protobuf type {@code Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              field_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fieldIntName_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fieldOption_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                fieldStrings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              fieldStrings_.add(bs);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                fieldOptionIntegers_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              fieldOptionIntegers_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                fieldOptionIntegers_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                fieldOptionIntegers_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              Data2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = fieldGpbOption_.toBuilder();
              }
              fieldGpbOption_ = input.readMessage(Data2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fieldGpbOption_);
                fieldGpbOption_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 58: {
              Data2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = fieldGpbOptionEmpty_.toBuilder();
              }
              fieldGpbOptionEmpty_ = input.readMessage(Data2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fieldGpbOptionEmpty_);
                fieldGpbOptionEmpty_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 66: {
              Data2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = fieldGpb_.toBuilder();
              }
              fieldGpb_ = input.readMessage(Data2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fieldGpb_);
                fieldGpb_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          fieldStrings_ = fieldStrings_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          fieldOptionIntegers_ = java.util.Collections.unmodifiableList(fieldOptionIntegers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestMessage.internal_static_Data_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestMessage.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FIELD_FIELD_NUMBER = 1;
    private Object field_;
    /**
     * <code>optional string field = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string field = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public String getField() {
      Object ref = field_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          field_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string field = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFieldBytes() {
      Object ref = field_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD_INT_NAME_FIELD_NUMBER = 2;
    private int fieldIntName_;
    /**
     * <code>optional int32 field_int_name = 2;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public boolean hasFieldIntName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 field_int_name = 2;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public int getFieldIntName() {
      return fieldIntName_;
    }

    public static final int FIELD_OPTION_FIELD_NUMBER = 3;
    private int fieldOption_;
    /**
     * <code>optional int32 field_option = 3;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public boolean hasFieldOption() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 field_option = 3;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public int getFieldOption() {
      return fieldOption_;
    }

    public static final int FIELD_STRINGS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList fieldStrings_;
    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldStringsList() {
      return fieldStrings_;
    }
    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public int getFieldStringsCount() {
      return fieldStrings_.size();
    }
    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public String getFieldStrings(int index) {
      return fieldStrings_.get(index);
    }
    /**
     * <code>repeated string field_strings = 4;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFieldStringsBytes(int index) {
      return fieldStrings_.getByteString(index);
    }

    public static final int FIELD_OPTION_INTEGERS_FIELD_NUMBER = 5;
    private java.util.List<Integer> fieldOptionIntegers_;
    /**
     * <code>repeated int32 field_option_integers = 5;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public java.util.List<Integer>
        getFieldOptionIntegersList() {
      return fieldOptionIntegers_;
    }
    /**
     * <code>repeated int32 field_option_integers = 5;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public int getFieldOptionIntegersCount() {
      return fieldOptionIntegers_.size();
    }
    /**
     * <code>repeated int32 field_option_integers = 5;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public int getFieldOptionIntegers(int index) {
      return fieldOptionIntegers_.get(index);
    }

    public static final int FIELD_GPB_OPTION_FIELD_NUMBER = 6;
    private Data2 fieldGpbOption_;
    /**
     * <code>optional .Data2 field_gpb_option = 6;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public boolean hasFieldGpbOption() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Data2 field_gpb_option = 6;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public Data2 getFieldGpbOption() {
      return fieldGpbOption_;
    }
    /**
     * <code>optional .Data2 field_gpb_option = 6;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public Data2OrBuilder getFieldGpbOptionOrBuilder() {
      return fieldGpbOption_;
    }

    public static final int FIELD_GPB_OPTION_EMPTY_FIELD_NUMBER = 7;
    private Data2 fieldGpbOptionEmpty_;
    /**
     * <code>optional .Data2 field_gpb_option_empty = 7;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public boolean hasFieldGpbOptionEmpty() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .Data2 field_gpb_option_empty = 7;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public Data2 getFieldGpbOptionEmpty() {
      return fieldGpbOptionEmpty_;
    }
    /**
     * <code>optional .Data2 field_gpb_option_empty = 7;</code>
     *
     * <pre>
     * OPTIONAL
     * </pre>
     */
    public Data2OrBuilder getFieldGpbOptionEmptyOrBuilder() {
      return fieldGpbOptionEmpty_;
    }

    public static final int FIELD_GPB_FIELD_NUMBER = 8;
    private Data2 fieldGpb_;
    /**
     * <code>optional .Data2 field_gpb = 8;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public boolean hasFieldGpb() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .Data2 field_gpb = 8;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public Data2 getFieldGpb() {
      return fieldGpb_;
    }
    /**
     * <code>optional .Data2 field_gpb = 8;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public Data2OrBuilder getFieldGpbOrBuilder() {
      return fieldGpb_;
    }

    private void initFields() {
      field_ = "";
      fieldIntName_ = 0;
      fieldOption_ = 0;
      fieldStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fieldOptionIntegers_ = java.util.Collections.emptyList();
      fieldGpbOption_ = Data2.getDefaultInstance();
      fieldGpbOptionEmpty_ = Data2.getDefaultInstance();
      fieldGpb_ = Data2.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFieldBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, fieldIntName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, fieldOption_);
      }
      for (int i = 0; i < fieldStrings_.size(); i++) {
        output.writeBytes(4, fieldStrings_.getByteString(i));
      }
      for (int i = 0; i < fieldOptionIntegers_.size(); i++) {
        output.writeInt32(5, fieldOptionIntegers_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(6, fieldGpbOption_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(7, fieldGpbOptionEmpty_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(8, fieldGpb_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFieldBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fieldIntName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fieldOption_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldStrings_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fieldStrings_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldStringsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldOptionIntegers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(fieldOptionIntegers_.get(i));
        }
        size += dataSize;
        size += 1 * getFieldOptionIntegersList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, fieldGpbOption_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, fieldGpbOptionEmpty_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, fieldGpb_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestMessage.internal_static_Data_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestMessage.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.class, Builder.class);
      }

      // Construct using com.avast.cactus.TestMessage.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFieldGpbOptionFieldBuilder();
          getFieldGpbOptionEmptyFieldBuilder();
          getFieldGpbFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        field_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldIntName_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldOption_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        fieldOptionIntegers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        if (fieldGpbOptionBuilder_ == null) {
          fieldGpbOption_ = Data2.getDefaultInstance();
        } else {
          fieldGpbOptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (fieldGpbOptionEmptyBuilder_ == null) {
          fieldGpbOptionEmpty_ = Data2.getDefaultInstance();
        } else {
          fieldGpbOptionEmptyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (fieldGpbBuilder_ == null) {
          fieldGpb_ = Data2.getDefaultInstance();
        } else {
          fieldGpbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestMessage.internal_static_Data_descriptor;
      }

      public Data getDefaultInstanceForType() {
        return Data.getDefaultInstance();
      }

      public Data build() {
        Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Data buildPartial() {
        Data result = new Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.field_ = field_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fieldIntName_ = fieldIntName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fieldOption_ = fieldOption_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          fieldStrings_ = fieldStrings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.fieldStrings_ = fieldStrings_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          fieldOptionIntegers_ = java.util.Collections.unmodifiableList(fieldOptionIntegers_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.fieldOptionIntegers_ = fieldOptionIntegers_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        if (fieldGpbOptionBuilder_ == null) {
          result.fieldGpbOption_ = fieldGpbOption_;
        } else {
          result.fieldGpbOption_ = fieldGpbOptionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        if (fieldGpbOptionEmptyBuilder_ == null) {
          result.fieldGpbOptionEmpty_ = fieldGpbOptionEmpty_;
        } else {
          result.fieldGpbOptionEmpty_ = fieldGpbOptionEmptyBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        if (fieldGpbBuilder_ == null) {
          result.fieldGpb_ = fieldGpb_;
        } else {
          result.fieldGpb_ = fieldGpbBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data) {
          return mergeFrom((Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data other) {
        if (other == Data.getDefaultInstance()) return this;
        if (other.hasField()) {
          bitField0_ |= 0x00000001;
          field_ = other.field_;
          onChanged();
        }
        if (other.hasFieldIntName()) {
          setFieldIntName(other.getFieldIntName());
        }
        if (other.hasFieldOption()) {
          setFieldOption(other.getFieldOption());
        }
        if (!other.fieldStrings_.isEmpty()) {
          if (fieldStrings_.isEmpty()) {
            fieldStrings_ = other.fieldStrings_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFieldStringsIsMutable();
            fieldStrings_.addAll(other.fieldStrings_);
          }
          onChanged();
        }
        if (!other.fieldOptionIntegers_.isEmpty()) {
          if (fieldOptionIntegers_.isEmpty()) {
            fieldOptionIntegers_ = other.fieldOptionIntegers_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFieldOptionIntegersIsMutable();
            fieldOptionIntegers_.addAll(other.fieldOptionIntegers_);
          }
          onChanged();
        }
        if (other.hasFieldGpbOption()) {
          mergeFieldGpbOption(other.getFieldGpbOption());
        }
        if (other.hasFieldGpbOptionEmpty()) {
          mergeFieldGpbOptionEmpty(other.getFieldGpbOptionEmpty());
        }
        if (other.hasFieldGpb()) {
          mergeFieldGpb(other.getFieldGpb());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object field_ = "";
      /**
       * <code>optional string field = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public boolean hasField() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string field = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public String getField() {
        Object ref = field_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            field_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string field = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFieldBytes() {
        Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string field = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setField(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string field = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder clearField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field_ = getDefaultInstance().getField();
        onChanged();
        return this;
      }
      /**
       * <code>optional string field = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }

      private int fieldIntName_ ;
      /**
       * <code>optional int32 field_int_name = 2;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public boolean hasFieldIntName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 field_int_name = 2;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public int getFieldIntName() {
        return fieldIntName_;
      }
      /**
       * <code>optional int32 field_int_name = 2;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldIntName(int value) {
        bitField0_ |= 0x00000002;
        fieldIntName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 field_int_name = 2;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder clearFieldIntName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldIntName_ = 0;
        onChanged();
        return this;
      }

      private int fieldOption_ ;
      /**
       * <code>optional int32 field_option = 3;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public boolean hasFieldOption() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 field_option = 3;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public int getFieldOption() {
        return fieldOption_;
      }
      /**
       * <code>optional int32 field_option = 3;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder setFieldOption(int value) {
        bitField0_ |= 0x00000004;
        fieldOption_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 field_option = 3;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder clearFieldOption() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldOption_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fieldStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldStringsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          fieldStrings_ = new com.google.protobuf.LazyStringArrayList(fieldStrings_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldStringsList() {
        return fieldStrings_.getUnmodifiableView();
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public int getFieldStringsCount() {
        return fieldStrings_.size();
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public String getFieldStrings(int index) {
        return fieldStrings_.get(index);
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFieldStringsBytes(int index) {
        return fieldStrings_.getByteString(index);
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldStrings(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldStringsIsMutable();
        fieldStrings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder addFieldStrings(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldStringsIsMutable();
        fieldStrings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder addAllFieldStrings(
          Iterable<String> values) {
        ensureFieldStringsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldStrings_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder clearFieldStrings() {
        fieldStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_strings = 4;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder addFieldStringsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldStringsIsMutable();
        fieldStrings_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<Integer> fieldOptionIntegers_ = java.util.Collections.emptyList();
      private void ensureFieldOptionIntegersIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          fieldOptionIntegers_ = new java.util.ArrayList<Integer>(fieldOptionIntegers_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 field_option_integers = 5;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public java.util.List<Integer>
          getFieldOptionIntegersList() {
        return java.util.Collections.unmodifiableList(fieldOptionIntegers_);
      }
      /**
       * <code>repeated int32 field_option_integers = 5;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public int getFieldOptionIntegersCount() {
        return fieldOptionIntegers_.size();
      }
      /**
       * <code>repeated int32 field_option_integers = 5;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public int getFieldOptionIntegers(int index) {
        return fieldOptionIntegers_.get(index);
      }
      /**
       * <code>repeated int32 field_option_integers = 5;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder setFieldOptionIntegers(
          int index, int value) {
        ensureFieldOptionIntegersIsMutable();
        fieldOptionIntegers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 field_option_integers = 5;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder addFieldOptionIntegers(int value) {
        ensureFieldOptionIntegersIsMutable();
        fieldOptionIntegers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 field_option_integers = 5;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder addAllFieldOptionIntegers(
          Iterable<? extends Integer> values) {
        ensureFieldOptionIntegersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldOptionIntegers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 field_option_integers = 5;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder clearFieldOptionIntegers() {
        fieldOptionIntegers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private Data2 fieldGpbOption_ = Data2.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Data2, Data2.Builder, Data2OrBuilder> fieldGpbOptionBuilder_;
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public boolean hasFieldGpbOption() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Data2 getFieldGpbOption() {
        if (fieldGpbOptionBuilder_ == null) {
          return fieldGpbOption_;
        } else {
          return fieldGpbOptionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldGpbOption(Data2 value) {
        if (fieldGpbOptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fieldGpbOption_ = value;
          onChanged();
        } else {
          fieldGpbOptionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldGpbOption(
          Data2.Builder builderForValue) {
        if (fieldGpbOptionBuilder_ == null) {
          fieldGpbOption_ = builderForValue.build();
          onChanged();
        } else {
          fieldGpbOptionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder mergeFieldGpbOption(Data2 value) {
        if (fieldGpbOptionBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              fieldGpbOption_ != Data2.getDefaultInstance()) {
            fieldGpbOption_ =
              Data2.newBuilder(fieldGpbOption_).mergeFrom(value).buildPartial();
          } else {
            fieldGpbOption_ = value;
          }
          onChanged();
        } else {
          fieldGpbOptionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder clearFieldGpbOption() {
        if (fieldGpbOptionBuilder_ == null) {
          fieldGpbOption_ = Data2.getDefaultInstance();
          onChanged();
        } else {
          fieldGpbOptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Data2.Builder getFieldGpbOptionBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getFieldGpbOptionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Data2OrBuilder getFieldGpbOptionOrBuilder() {
        if (fieldGpbOptionBuilder_ != null) {
          return fieldGpbOptionBuilder_.getMessageOrBuilder();
        } else {
          return fieldGpbOption_;
        }
      }
      /**
       * <code>optional .Data2 field_gpb_option = 6;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Data2, Data2.Builder, Data2OrBuilder>
          getFieldGpbOptionFieldBuilder() {
        if (fieldGpbOptionBuilder_ == null) {
          fieldGpbOptionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Data2, Data2.Builder, Data2OrBuilder>(
                  getFieldGpbOption(),
                  getParentForChildren(),
                  isClean());
          fieldGpbOption_ = null;
        }
        return fieldGpbOptionBuilder_;
      }

      private Data2 fieldGpbOptionEmpty_ = Data2.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Data2, Data2.Builder, Data2OrBuilder> fieldGpbOptionEmptyBuilder_;
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public boolean hasFieldGpbOptionEmpty() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Data2 getFieldGpbOptionEmpty() {
        if (fieldGpbOptionEmptyBuilder_ == null) {
          return fieldGpbOptionEmpty_;
        } else {
          return fieldGpbOptionEmptyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder setFieldGpbOptionEmpty(Data2 value) {
        if (fieldGpbOptionEmptyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fieldGpbOptionEmpty_ = value;
          onChanged();
        } else {
          fieldGpbOptionEmptyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder setFieldGpbOptionEmpty(
          Data2.Builder builderForValue) {
        if (fieldGpbOptionEmptyBuilder_ == null) {
          fieldGpbOptionEmpty_ = builderForValue.build();
          onChanged();
        } else {
          fieldGpbOptionEmptyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder mergeFieldGpbOptionEmpty(Data2 value) {
        if (fieldGpbOptionEmptyBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              fieldGpbOptionEmpty_ != Data2.getDefaultInstance()) {
            fieldGpbOptionEmpty_ =
              Data2.newBuilder(fieldGpbOptionEmpty_).mergeFrom(value).buildPartial();
          } else {
            fieldGpbOptionEmpty_ = value;
          }
          onChanged();
        } else {
          fieldGpbOptionEmptyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Builder clearFieldGpbOptionEmpty() {
        if (fieldGpbOptionEmptyBuilder_ == null) {
          fieldGpbOptionEmpty_ = Data2.getDefaultInstance();
          onChanged();
        } else {
          fieldGpbOptionEmptyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Data2.Builder getFieldGpbOptionEmptyBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getFieldGpbOptionEmptyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      public Data2OrBuilder getFieldGpbOptionEmptyOrBuilder() {
        if (fieldGpbOptionEmptyBuilder_ != null) {
          return fieldGpbOptionEmptyBuilder_.getMessageOrBuilder();
        } else {
          return fieldGpbOptionEmpty_;
        }
      }
      /**
       * <code>optional .Data2 field_gpb_option_empty = 7;</code>
       *
       * <pre>
       * OPTIONAL
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Data2, Data2.Builder, Data2OrBuilder>
          getFieldGpbOptionEmptyFieldBuilder() {
        if (fieldGpbOptionEmptyBuilder_ == null) {
          fieldGpbOptionEmptyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Data2, Data2.Builder, Data2OrBuilder>(
                  getFieldGpbOptionEmpty(),
                  getParentForChildren(),
                  isClean());
          fieldGpbOptionEmpty_ = null;
        }
        return fieldGpbOptionEmptyBuilder_;
      }

      private Data2 fieldGpb_ = Data2.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Data2, Data2.Builder, Data2OrBuilder> fieldGpbBuilder_;
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public boolean hasFieldGpb() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Data2 getFieldGpb() {
        if (fieldGpbBuilder_ == null) {
          return fieldGpb_;
        } else {
          return fieldGpbBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldGpb(Data2 value) {
        if (fieldGpbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fieldGpb_ = value;
          onChanged();
        } else {
          fieldGpbBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldGpb(
          Data2.Builder builderForValue) {
        if (fieldGpbBuilder_ == null) {
          fieldGpb_ = builderForValue.build();
          onChanged();
        } else {
          fieldGpbBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder mergeFieldGpb(Data2 value) {
        if (fieldGpbBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              fieldGpb_ != Data2.getDefaultInstance()) {
            fieldGpb_ =
              Data2.newBuilder(fieldGpb_).mergeFrom(value).buildPartial();
          } else {
            fieldGpb_ = value;
          }
          onChanged();
        } else {
          fieldGpbBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder clearFieldGpb() {
        if (fieldGpbBuilder_ == null) {
          fieldGpb_ = Data2.getDefaultInstance();
          onChanged();
        } else {
          fieldGpbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Data2.Builder getFieldGpbBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getFieldGpbFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Data2OrBuilder getFieldGpbOrBuilder() {
        if (fieldGpbBuilder_ != null) {
          return fieldGpbBuilder_.getMessageOrBuilder();
        } else {
          return fieldGpb_;
        }
      }
      /**
       * <code>optional .Data2 field_gpb = 8;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Data2, Data2.Builder, Data2OrBuilder>
          getFieldGpbFieldBuilder() {
        if (fieldGpbBuilder_ == null) {
          fieldGpbBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Data2, Data2.Builder, Data2OrBuilder>(
                  getFieldGpb(),
                  getParentForChildren(),
                  isClean());
          fieldGpb_ = null;
        }
        return fieldGpbBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Data)
  }

  public interface Data2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double field_double = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    boolean hasFieldDouble();
    /**
     * <code>optional double field_double = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    double getFieldDouble();
  }
  /**
   * Protobuf type {@code Data2}
   */
  public static final class Data2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Data2)
      Data2OrBuilder {
    // Use Data2.newBuilder() to construct.
    private Data2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data2 defaultInstance;
    public static Data2 getDefaultInstance() {
      return defaultInstance;
    }

    public Data2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              fieldDouble_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestMessage.internal_static_Data2_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestMessage.internal_static_Data2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data2.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Data2> PARSER =
        new com.google.protobuf.AbstractParser<Data2>() {
      public Data2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data2(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Data2> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FIELD_DOUBLE_FIELD_NUMBER = 1;
    private double fieldDouble_;
    /**
     * <code>optional double field_double = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public boolean hasFieldDouble() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double field_double = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public double getFieldDouble() {
      return fieldDouble_;
    }

    private void initFields() {
      fieldDouble_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, fieldDouble_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, fieldDouble_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Data2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Data2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Data2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Data2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Data2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Data2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data2)
        Data2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestMessage.internal_static_Data2_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestMessage.internal_static_Data2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data2.class, Builder.class);
      }

      // Construct using com.avast.cactus.TestMessage.Data2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fieldDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestMessage.internal_static_Data2_descriptor;
      }

      public Data2 getDefaultInstanceForType() {
        return Data2.getDefaultInstance();
      }

      public Data2 build() {
        Data2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Data2 buildPartial() {
        Data2 result = new Data2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fieldDouble_ = fieldDouble_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data2) {
          return mergeFrom((Data2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data2 other) {
        if (other == Data2.getDefaultInstance()) return this;
        if (other.hasFieldDouble()) {
          setFieldDouble(other.getFieldDouble());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Data2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Data2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double fieldDouble_ ;
      /**
       * <code>optional double field_double = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public boolean hasFieldDouble() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double field_double = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public double getFieldDouble() {
        return fieldDouble_;
      }
      /**
       * <code>optional double field_double = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setFieldDouble(double value) {
        bitField0_ |= 0x00000001;
        fieldDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double field_double = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder clearFieldDouble() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldDouble_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Data2)
    }

    static {
      defaultInstance = new Data2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Data2)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Data2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022test_message.proto\"\336\001\n\004Data\022\r\n\005field\030\001" +
      " \001(\t\022\026\n\016field_int_name\030\002 \001(\005\022\024\n\014field_op" +
      "tion\030\003 \001(\005\022\025\n\rfield_strings\030\004 \003(\t\022\035\n\025fie" +
      "ld_option_integers\030\005 \003(\005\022 \n\020field_gpb_op" +
      "tion\030\006 \001(\0132\006.Data2\022&\n\026field_gpb_option_e" +
      "mpty\030\007 \001(\0132\006.Data2\022\031\n\tfield_gpb\030\010 \001(\0132\006." +
      "Data2\"\035\n\005Data2\022\024\n\014field_double\030\001 \001(\001B\022\n\020" +
      "com.avast.cactus"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Data_descriptor,
        new String[] { "Field", "FieldIntName", "FieldOption", "FieldStrings", "FieldOptionIntegers", "FieldGpbOption", "FieldGpbOptionEmpty", "FieldGpb", });
    internal_static_Data2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Data2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Data2_descriptor,
        new String[] { "FieldDouble", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
